/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "coral-watermelon-vivid": "#FF5376",
        "primary-fixed-dim": "#b4c5ff",
        "secondary": "#ad2c4f",
        "surface": "#fbf8fc",
        "aqi-unhealthy": "#F97316",
        "primary-container": "#2563eb",
        "secondary-container": "#fd6989",
        "aqi-severe": "#FF5376",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f6f2f7",
        "tertiary-fixed": "#ffdbca",
        "secondary-fixed-dim": "#ffb2bd",
        "inverse-surface": "#303033",
        "surface-container-lowest": "#ffffff",
        "canvas-cream": "#FAF6EE",
        "ink-muted": "#52525B",
        "surface-tint": "#0053db",
        "inverse-primary": "#b4c5ff",
        "forest-jade": "#10B981",
        "tertiary-container": "#b54e00",
        "on-tertiary": "#ffffff",
        "ink-black": "#18181B",
        "aqi-moderate": "#F59E0B",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#003ea8",
        "error-container": "#ffdad6",
        "outline": "#737686",
        "aqi-hazardous": "#7C2D12",
        "terracotta-deep": "#EA580C",
        "on-tertiary-fixed": "#341100",
        "surface-container-high": "#eae7eb",
        "surface-dim": "#dcd9dd",
        "aqi-good": "#10B981",
        "on-primary-container": "#eeefff",
        "outline-variant": "#c3c6d7",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e1e6",
        "on-background": "#1b1b1e",
        "on-tertiary-container": "#ffece5",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#f3f0f4",
        "on-surface-variant": "#434655",
        "on-secondary-fixed": "#400014",
        "primary": "#004ac6",
        "surface-bright": "#fbf8fc",
        "surface-vanilla": "#F7F3E9",
        "secondary-fixed": "#ffd9dd",
        "surface-container": "#f0edf1",
        "on-tertiary-fixed-variant": "#783200",
        "background": "#fbf8fc",
        "surface-container-highest": "#e4e1e6",
        "on-secondary-fixed-variant": "#8c1038",
        "tertiary-fixed-dim": "#ffb690",
        "on-surface": "#1b1b1e",
        "cobalt-deep": "#1D4ED8",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00174b",
        "surface-vanilla-strong": "#EFE9DA",
        "on-secondary-container": "#6b0027",
        "tertiary": "#8e3c00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-3xl": "4rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "container-max": "1280px",
        "gutter-desktop": "1.5rem",
        "space-2xl": "3rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "gutter-mobile": "1rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        "headline-sm": ["Newsreader", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Newsreader", "serif"],
        "display-lg-mobile": ["Newsreader", "serif"],
        "telemetry-unit": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "telemetry-val": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "26px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "title-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "54px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "telemetry-unit": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "title-sm": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "telemetry-val": ["22px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
