/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f4",
        "surface-dim": "#dcdad5",
        "surface-bright": "#fcf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ee",
        "surface-container": "#f0ede9",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e5e2dd",
        "on-surface": "#1c1c19",
        "on-surface-variant": "#444748",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f3f0eb",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        "secondary": "#b61b00",
        "on-secondary": "#ffffff",
        "secondary-container": "#db3417",
        "on-secondary-container": "#fffbff",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#241a00",
        "on-tertiary-container": "#a37f00",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed": "#ffdad3",
        "secondary-fixed-dim": "#ffb4a5",
        "on-secondary-fixed": "#3f0400",
        "on-secondary-fixed-variant": "#8e1300",
        "tertiary-fixed": "#ffdf93",
        "tertiary-fixed-dim": "#eec145",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#594400",
        "background": "#fcf9f4",
        "on-background": "#1c1c19",
        "surface-variant": "#e5e2dd",
        "accent-blue": "#2563eb",
        "accent-emerald": "#10b981",
        "border-subtle": "#e2ded7",
        "border-strong": "#111111"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit-2xs": "0.25rem",
        "unit-xs": "0.5rem",
        "unit-sm": "0.75rem",
        "unit-md": "1rem",
        "unit-lg": "1.5rem",
        "unit-xl": "2rem",
        "unit-2xl": "3rem",
        "unit-3xl": "4rem",
        "gutter-mobile": "1.25rem",
        "gutter-desktop": "2rem",
        "max-width-content": "440px"
      },
      fontFamily: {
        "sans": ["DM Sans", "-apple-system", "sans-serif"],
        "serif": ["Newsreader", "serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "display-lg": ["Newsreader", "serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "label-lg": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "label-sm": ["DM Sans", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
